*Pattern Recognition*
  - Course: ENCE 3630 and ENCE 4630 2017
  - Instructor: /Pooran Singh Negi, pooran.negi@gmail.com/
  - Office: 248
  - Office Hours: After the class T, Th,  3.50- 4.50. Email for 1-on-1 help.
* TextBooks
- *Required:*  [[https://www.cs.ubc.ca/~murphyk/MLbook/][Machine Learning: a Probabilistic Perspective by Kevin Patrick Murphy]]. Online version is available in the library.
- *Optional:* [[http://www-bcf.usc.edu/~gareth/ISL/][An Introduction to Statistical Learning by Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani]]. It is available online in pdf format
- *Optional:* For more advance treatment [[https://web.stanford.edu/~hastie/ElemStatLearn/][The Elements of Statistical Learning]]. It is available online in pdf format   
* Course Description
Pattern recognition is in exciting area. We will go though theory behind
pattern recognition using tool from probability and linear algebra.
We will use python, its [[https://www.scipy.org/][scientific libraries]] (numpy, scipy, matplotlib etc.)
and [[http://scikit-learn.org/stable/][scikit-learn: Machine Learning in Python]] during the course. For deep neural network part, we will use
highly pouplar [[https://www.tensorflow.org/][tensorflow Machine Intelligence]] library
from the Google. One can use other languages and tools as per comfort level. 
At the end of the course one should be able to understand theory behind various
machine learning algorithms, be comfortable using open source tool for pattern recognition.

* Software
Please install [[https://www.anaconda.com/download/][Anaconda for Python 2.7 data science platform.
]]For Deep Neural networks, we will go over installation instruction later in the course.
* Prerequisite
Student should be comfortable with linear algebra, probability, statistics
and some programming experience. We will cover basics in the class.

* Syllabus
Here are the main topics for the class
- Basic idea of machine learning, and probability
- Generative models, parametric estimation and supervised learning.
  - Naive Bayes classifier
- Gaussian models
- Linear and logistic regression
- Support vector machine, Kernels
- Unsupervised learning
  - Clustering
- Deep learning
  - Artificial Neural Networks(ANN)
  - Convolutional Neural Networks(CNN) for classification and regression
  - Recurrent Neural Networks for natural language processing(NLP) and time series data
* Grading
There will be one mid term and a final, homework assignments, in class quizzes and project assignments.
Worst 2 of your homework assignments and 2 quizzes will be dropped.

|----------+-------------------------+-------------------|
|          | Under Graduate students | Graduate students |
|----------+-------------------------+-------------------|
| Homework | 40 %                    |               25% |
|----------+-------------------------+-------------------|
| Midterm  | 30%                     |               25% |
|----------+-------------------------+-------------------|
| Final    | 30 %                    |               30% |
|----------+-------------------------+-------------------|
| Project  |                         |               20% |
|----------+-------------------------+-------------------|


